//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventorymanager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventoryEntities1 : DbContext
    {
        public inventoryEntities1()
            : base("name=inventoryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cityid> cityids { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<storeid> storeids { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<storetype> storetypes { get; set; }
        public virtual DbSet<worker> workers { get; set; }
    }
}
