//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventorymanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int item_number { get; set; }
        public int inventoryid { get; set; }
        public int itemid { get; set; }
        public int quantity { get; set; }
        public int cost { get; set; }
        public int sale_price { get; set; }
    
        public virtual item item { get; set; }
        public virtual store store { get; set; }
    }
}
