//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventorymanager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventoryEntities : DbContext
    {
        public inventoryEntities()
            : base("name=inventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<citylist> citylists { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<storelist> storelists { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<storetypelist> storetypelists { get; set; }
        public virtual DbSet<worker> workers { get; set; }
    }
}
