//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventorymanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public int storenumber { get; set; }
        public int storeID { get; set; }
        public int inventoryid { get; set; }
        public int cityid { get; set; }
        public int storephone { get; set; }
        public int StoreType { get; set; }
    
        public virtual cityid cityid1 { get; set; }
        public virtual inventory inventory { get; set; }
        public virtual storeid storeid1 { get; set; }
        public virtual storetype storetype1 { get; set; }
    }
}
