//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventorymanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public store()
        {
            this.inventories = new HashSet<inventory>();
        }
    
        public int storenumber { get; set; }
        public int storeID { get; set; }
        public int inventoryid { get; set; }
        public int cityid { get; set; }
        public int storephone { get; set; }
        public int StoreType { get; set; }
    
        public virtual citylist citylist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory> inventories { get; set; }
        public virtual storelist storelist { get; set; }
        public virtual storetypelist storetypelist { get; set; }
    }
}
